modules:
    pvptag:
        enabled: true
        duration: 20
        blockedcmds:
            - j
            - jumpto
            - warp
            - home
            - spawn
            - fly
            - jumpto
            - tpa
            - tpahere
            - v
    pvplog:
        enabled: false
        duration: 60
    pvpblock:
        enabled: false
        allow_attack: true
    pvpblockpassword:
        enabled: false
        default_password: strength
    playertracker:
        enabled: true
        trackdistance: 350
    pvpfly:
        enabled: true
