modules:
    pvptag:
        enabled: true
        duration: 20
        blockedcmds:
            - j
            - warp
            - home
            - fly
            - jumpto
            - tpa
            - tpahere
            - v
    pvplog:
        enabled: false
    pvpblock:
        enabled: true
        allow_attack: true
