modules:
    pvptag:
        enabled: true
        duration: 20
        blockedcmds:
            - j
            - jumpto
            - warp
            - home
            - spawn
            - fly
            - jumpto
            - tpa
            - tpahere
            - back
            - top
            - v
            - c windwalk
    pvplog:
        enabled: true
        duration: 120
    pvpblock:
        enabled: false
        allow_attack: true
    pvpblockpassword:
        enabled: false
        default_password: strength
    playertracker:
        enabled: true
        trackdistance: 350
    pvpfly:
        enabled: true
upm: true
upm_update: http://www.pvp.mcs.square7.ch/pvptoolkit.json
upm_configtype:
    modules:
        pvptag:
            enabled: boolean
            duration: int
            blockedcmds: list
        pvplog:
            enabled: boolean
            duration: int
        pvpblock:
            enabled: boolean
            allow_attack: boolean
        pvpblockpassword:
            enabled: boolean
            default_password: string
        playertracker:
            enabled: boolean
            trackdistance: int
        pvpfly:
            enabled: boolean