modules:
    pvptag:
        enabled: true
        duration: 20
        blockedcmds:
            - j
            - jumpto
            - warp
            - home
            - spawn
            - fly
            - jumpto
            - tpa
            - tpahere
            - back
            - top
            - v
            - c windwalk
    pvplog:
        enabled: true
        duration: 120
    playertracker:
        enabled: true
        smalltrackdistance: 350
        advancedtrackdistance: 700
    pvpfly:
        enabled: true
    spawnprotect:
        enabled: true
        radius: 2
upm: true
upm_update: http://www.pvp.mcs.square7.ch/pvptoolkit.json
upm_configtype:
    modules:
        pvptag:
            enabled: boolean
            duration: int
            blockedcmds: list
        pvplog:
            enabled: boolean
            duration: int
        playertracker:
            enabled: boolean
            smalltrackdistance: int
            advancedtrackdistance: int
        pvpfly:
            enabled: boolean
        spawnprotect:
            enabled: boolean
            radius: int