modules:
    pvptag:
        enabled: true
        duration: 20
        blockedcmds:
            - j
            - warp
            - home
            - fly
            - jumpto
    pvplog:
        enabled: false
